### ISSUE TITLE
shape error when render a video

### ISSUE THREAD

**Issue by ZiyangYan** [google-research/multinerf#138]
when I want to render a video from checkpoint, it raised a error:

--------------------------------------------------------------------------------------
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyan/anaconda3/envs/multinerf/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zyan/anaconda3/envs/multinerf/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/3DOM/zyan/multinerf-main/render.py", line 204, in <module>
    app.run(main)
  File "/home/zyan/anaconda3/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/zyan/anaconda3/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/scratch/3DOM/zyan/multinerf-main/render.py", line 155, in main
    rendering = models.render_image(
  File "/scratch/3DOM/zyan/multinerf-main/internal/models.py", line 673, in render_image
    chunk_renderings, _ = render_fn(rng, chunk_rays)
  File "/scratch/3DOM/zyan/multinerf-main/internal/train_utils.py", line 382, in render_eval_fn
    model.apply(
  File "/scratch/3DOM/zyan/multinerf-main/internal/models.py", line 223, in __call__
    ray_results = mlp(
  File "/scratch/3DOM/zyan/multinerf-main/internal/models.py", line 469, in __call__
    raw_density, x = predict_density(means, covs)
  File "/scratch/3DOM/zyan/multinerf-main/internal/models.py", line 456, in predict_density
    x = dense_layer(self.net_width)(x)
  File "/home/zyan/anaconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py", line 234, in __call__
    kernel = self.param(
flax.errors.ScopeParamShapeError: Initializer expected to generate shape (672, 256) but got shape (96, 256) instead for parameter "kernel" in "/PropMLP_0/Dense_0". (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeParamShapeError)
---------------------------------------------------------------------------------------------------------------------------------------------

anybody know how to deal with it?

**Comment by ZiyangYan** [comment]
fixed

**Comment by Snehan2k2** [comment]
how did you resolve the error?

**Comment by andrewyguo** [comment]
@ZiyangYan  how did you fix it?

**Comment by ZiyangYan** [comment]
> @ZiyangYan how did you fix it?

sorry bro, it already more than one year ago, I don't remember the detail
