### ISSUE TITLE
flax.errors.ScopeParamShapeError

### ISSUE THREAD

**Issue by andrewyguo** [google-research/multinerf#163]
Getting the error: 

```
flax.errors.ScopeParamShapeError: Initializer expected to generate shape (96, 256) but got shape (504, 256) instead for parameter "kernel" in "/NerfMLP_0/Dense_0". (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeParamShapeError)
```

This happens when during render time. 

I am training using the default configs in `llff_raw.gin` with the command: 
```
DATA_DIR="data/scenes/bikes"
python -m train \
  --gin_configs=configs/llff_raw.gin \
  --gin_bindings="Config.data_dir = '${DATA_DIR}'" \
  --gin_bindings="Config.checkpoint_dir = '${DATA_DIR}/checkpoints'" \
  --logtostderr
```

And then when I render:

```
python -m render \
  --gin_bindings="Config.data_dir = '${DATA_DIR}'" \
  --gin_bindings="Config.checkpoint_dir = '${DATA_DIR}/checkpoints'" \
  --gin_bindings="Config.render_dir = '${DATA_DIR}/render'" \
  --gin_bindings="Config.render_path = True" \
  --gin_bindings="Config.render_path_frames = 20" \
  --gin_bindings="Config.render_video_fps = 1" \
  --logtostderr
```

The error appears. Here is the full log: 

```
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/local/user/miniconda3/envs/multinerf/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/local/user/miniconda3/envs/multinerf/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/local3/2024/user/Documents/multinerf/render.py", line 204, in <module>
    app.run(main)
  File "/scratch/local/user/miniconda3/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/scratch/local/user/miniconda3/envs/multinerf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/scratch/local3/2024/user/Documents/multinerf/render.py", line 155, in main
    rendering = models.render_image(
  File "/scratch/local3/2024/user/Documents/multinerf/internal/models.py", line 690, in render_image
    chunk_renderings, _ = render_fn(rng, chunk_rays)
  File "/scratch/local3/2024/user/Documents/multinerf/internal/train_utils.py", line 382, in render_eval_fn
    model.apply(
  File "/scratch/local3/2024/user/Documents/multinerf/internal/models.py", line 231, in __call__
    ray_results = mlp(
  File "/scratch/local3/2024/user/Documents/multinerf/internal/models.py", line 498, in __call__
    predict_density_and_grad_fn(means_flat, covs_flat))
  File "/scratch/local3/2024/user/Documents/multinerf/internal/models.py", line 469, in predict_density
    x = dense_layer(self.net_width)(x)
  File "/scratch/local/user/miniconda3/envs/multinerf/lib/python3.9/site-packages/flax/linen/linear.py", line 256, in __call__
    kernel = self.param(
flax.errors.ScopeParamShapeError: Initializer expected to generate shape (256, 256) but got shape (504, 256) instead for parameter "kernel" in "/NerfMLP_0/Dense_1". (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeParamShapeError)

```

**Comment by andrewyguo** [comment]
Fixed. This error was happening because of a mismatch between the config file I was passing in for training and the one I was passing in for render. I fixed by passing in the same config .gin file for training and render
